name: Generate Mermaid Diagrams

on:
  push:
    branches:
      - main # Or any branch where you want this to run
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Or '18.x', 'lts/*', etc.

      - name: Install mermaid-cli globally
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Verify mermaid-cli installation
        run: mmdc --version

      - name: Generate diagram (example)
        run: |
          echo "graph TD" > example.mmd
          echo "    A[Start] --> B(Process)" >> example.mmd
          echo "    B --> C{Decision}" >> example.mmd
          echo "    C -- Yes --> D[End]" >> example.mmd
          echo "    C -- No --> B" >> example.mmd

          mmdc -i example.mmd -o example.svg -t forest -b transparent

      - name: Upload generated diagram as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermaid-diagrams
          path: example.svg # Or a directory if you generate multiple

